insert into software(id, name) VALUES (1, 'leadscope')
insert into software(id, name) VALUES (2, 'vega')
insert into software(id, name) VALUES (3, 'qsar toolbox')
insert into software(id, name) VALUES (4, 'acd perceptra')
insert into software(id, name) VALUES (5, 'opera')
insert into software(id, name) VALUES (6, 'test')

insert into endpoint(id, name) VALUES(1,'sperm effect')
insert into endpoint(id, name) VALUES(2,'reproductive toxicity')
insert into endpoint(id, name) VALUES(3,'mutagenicity')
insert into endpoint(id, name) VALUES(4,'carcinogenicity')
